-- Insert default user types
INSERT INTO user_types (name, created_at, updated_at)
VALUES
    ('ADMIN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('RESTAURANT_OWNER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('CUSTOMER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

